### ISSUE TITLE
Refactoring in order

### ISSUE THREAD

**Issue by mrlesmithjr** [mrlesmithjr/ansible-manage-lvm#37]
This role is due for some code refactoring love, etc.

**Comment by Tcharl** [comment]
Hi @mrlesmithjr ,

FYI, I find out how to mount virtual disk in a travis job: so that you can add molecule->vagrant-libvirt tests on LVM in a travis pipeline :-).
I achieved that [here](https://github.com/Tcharl/ansible-volumes/tree/platform-43/molecule/kvm), and may contribute to some third party repositories (for example this one), but it would come in mid term if it comes from me
